

trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: Docker@2
      inputs:
        containerRegistry: 'tarun_repo_connector'
        repository: 'tarun_python_test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 
          $(Build.SourceVersion)
          
    - bash: echo Contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)        
    - bash: echo Before copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)        