apiVersion: apps/v1
kind: Deployment 
metadata:
  name: python-app
  labels:
    app: python-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template: 
    metadata:
      labels: 
        app: python-app
        tier: frontend
    spec: 
      containers: 
        - name: python-app
          image: tarunrepo.azurecr.io/tarun_python_test
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service 
metadata:
  name: tarun-python-service
  labels:
    app: python-app
    tier: frontend  
spec:
  type: LoadBalancer 
  selector:
    app: python-app
  ports: 
    - name: http
      port: 5000 
      targetPort: 5000


